registerCards([
  {
    "id": 311,
    "n": "Espada do Faraó",
    "kind": "equip",
    "target": "monster",
    "atkBonus": 500,
    "defBonus": 0,
    "t": "Equipamento",
    "g": "Sol",
    "e": "Luz",
    "art": "🗡️",
    "rarity": "R",
    "family": "equipamentos",
    "desc": "+500 ATK."
  },
  {
    "id": 312,
    "n": "Escudo de Obsidiana",
    "kind": "equip",
    "target": "monster",
    "atkBonus": 0,
    "defBonus": 600,
    "t": "Equipamento",
    "g": "Plutão",
    "e": "Trevas",
    "art": "🛡️",
    "rarity": "R",
    "family": "equipamentos",
    "desc": "+600 DEF."
  },
  {
    "id": 313,
    "n": "Tesouro do Dragão",
    "kind": "equip",
    "target": "Dragão",
    "atkBonus": 700,
    "defBonus": 300,
    "t": "Equipamento",
    "g": "Marte",
    "e": "Fogo",
    "art": "💎",
    "rarity": "SR",
    "family": "equipamentos",
    "desc": "+700 ATK / +300 DEF para Dragões."
  },
  {
    "id": 314,
    "n": "Livro do Poder",
    "kind": "equip",
    "target": "Mago",
    "atkBonus": 600,
    "defBonus": 200,
    "t": "Equipamento",
    "g": "Mercúrio",
    "e": "Luz",
    "art": "📕",
    "rarity": "SR",
    "family": "equipamentos",
    "desc": "+600 ATK / +200 DEF para Magos."
  },
  {
    "id": 315,
    "n": "Asas de Prata",
    "kind": "equip",
    "target": "Pássaro",
    "atkBonus": 650,
    "defBonus": 250,
    "t": "Equipamento",
    "g": "Saturno",
    "e": "Vento",
    "art": "🪽",
    "rarity": "SR",
    "family": "equipamentos",
    "desc": "+650 ATK / +250 DEF para Pássaros."
  }
]);
