registerCards([
  {
    "id": 201,
    "n": "Cavaleiro Dragão",
    "a": 2400,
    "d": 1950,
    "t": "Dragão",
    "g": "Marte",
    "e": "Fogo",
    "art": "🐲",
    "rarity": "SR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 202,
    "n": "Paladino Sombrio",
    "a": 2350,
    "d": 2050,
    "t": "Guerreiro",
    "g": "Lua",
    "e": "Trevas",
    "art": "👑",
    "rarity": "SR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 203,
    "n": "Quimera do Vendaval",
    "a": 2250,
    "d": 2150,
    "t": "Besta",
    "g": "Saturno",
    "e": "Vento",
    "art": "🌀",
    "rarity": "SR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 204,
    "n": "Mago do Eclipse",
    "a": 2500,
    "d": 2100,
    "t": "Mago",
    "g": "Mercúrio",
    "e": "Trevas",
    "art": "🌘",
    "rarity": "SR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 205,
    "n": "Imperatriz Astral",
    "a": 2600,
    "d": 2350,
    "t": "Fada",
    "g": "Vênus",
    "e": "Luz",
    "art": "⭐",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 206,
    "n": "Dragão do Caos",
    "a": 2850,
    "d": 2450,
    "t": "Dragão",
    "g": "Plutão",
    "e": "Trevas",
    "art": "🐲",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 207,
    "n": "Titã Vulcânico",
    "a": 2550,
    "d": 2250,
    "t": "Rocha",
    "g": "Marte",
    "e": "Fogo",
    "art": "🌋",
    "rarity": "SR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 208,
    "n": "Leviatã Tempestuoso",
    "a": 2700,
    "d": 2300,
    "t": "Aqua",
    "g": "Netuno",
    "e": "Água",
    "art": "🌊",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 209,
    "n": "Fênix Imperial",
    "a": 2750,
    "d": 2100,
    "t": "Pássaro",
    "g": "Sol",
    "e": "Fogo",
    "art": "🔥",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 210,
    "n": "Dragão Celestial",
    "a": 3000,
    "d": 2500,
    "t": "Dragão",
    "g": "Sol",
    "e": "Luz",
    "art": "🌟",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 211,
    "n": "Mago do Apocalipse",
    "a": 2900,
    "d": 2400,
    "t": "Mago",
    "g": "Plutão",
    "e": "Trevas",
    "art": "🌀",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 212,
    "n": "Rei das Máquinas",
    "a": 2800,
    "d": 2700,
    "t": "Máquina",
    "g": "Urano",
    "e": "Raio",
    "art": "🤖",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 213,
    "n": "Serafim do Eclipse",
    "a": 2850,
    "d": 2600,
    "t": "Fada",
    "g": "Lua",
    "e": "Luz",
    "art": "🪽",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 214,
    "n": "Hidra Vulcânica",
    "a": 2650,
    "d": 2200,
    "t": "Dragão",
    "g": "Marte",
    "e": "Fogo",
    "art": "🐲",
    "rarity": "SR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 215,
    "n": "Guardião do Firmamento",
    "a": 2950,
    "d": 2750,
    "t": "Guerreiro",
    "g": "Júpiter",
    "e": "Vento",
    "art": "⚔️",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  }
]);

registerCards([
  {
    "id": 408,
    "n": "Fusão Suprema 1",
    "a": 2600,
    "d": 2300,
    "t": "Dragão",
    "g": "Marte",
    "e": "Fogo",
    "art": "🐲",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 409,
    "n": "Fusão Suprema 2",
    "a": 2645,
    "d": 2340,
    "t": "Mago",
    "g": "Mercúrio",
    "e": "Trevas",
    "art": "🌌",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 410,
    "n": "Fusão Suprema 3",
    "a": 2690,
    "d": 2380,
    "t": "Pássaro",
    "g": "Saturno",
    "e": "Vento",
    "art": "🪽",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 411,
    "n": "Fusão Suprema 4",
    "a": 2735,
    "d": 2420,
    "t": "Guerreiro",
    "g": "Sol",
    "e": "Luz",
    "art": "⚔️",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 412,
    "n": "Fusão Suprema 5",
    "a": 2780,
    "d": 2460,
    "t": "Aqua",
    "g": "Netuno",
    "e": "Água",
    "art": "🌊",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 413,
    "n": "Fusão Suprema 6",
    "a": 2825,
    "d": 2500,
    "t": "Máquina",
    "g": "Urano",
    "e": "Raio",
    "art": "🤖",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 414,
    "n": "Fusão Suprema 7",
    "a": 2870,
    "d": 2540,
    "t": "Dragão",
    "g": "Marte",
    "e": "Fogo",
    "art": "🐲",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 415,
    "n": "Fusão Suprema 8",
    "a": 2915,
    "d": 2580,
    "t": "Mago",
    "g": "Mercúrio",
    "e": "Trevas",
    "art": "🌌",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 416,
    "n": "Fusão Suprema 9",
    "a": 2960,
    "d": 2620,
    "t": "Pássaro",
    "g": "Saturno",
    "e": "Vento",
    "art": "🪽",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 417,
    "n": "Fusão Suprema 10",
    "a": 3005,
    "d": 2660,
    "t": "Guerreiro",
    "g": "Sol",
    "e": "Luz",
    "art": "⚔️",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 418,
    "n": "Fusão Suprema 11",
    "a": 3050,
    "d": 2700,
    "t": "Aqua",
    "g": "Netuno",
    "e": "Água",
    "art": "🌊",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 419,
    "n": "Fusão Suprema 12",
    "a": 3095,
    "d": 2740,
    "t": "Máquina",
    "g": "Urano",
    "e": "Raio",
    "art": "🤖",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 420,
    "n": "Fusão Suprema 13",
    "a": 3140,
    "d": 2780,
    "t": "Dragão",
    "g": "Marte",
    "e": "Fogo",
    "art": "🐲",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 421,
    "n": "Fusão Suprema 14",
    "a": 3185,
    "d": 2820,
    "t": "Mago",
    "g": "Mercúrio",
    "e": "Trevas",
    "art": "🌌",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 422,
    "n": "Fusão Suprema 15",
    "a": 3230,
    "d": 2860,
    "t": "Pássaro",
    "g": "Saturno",
    "e": "Vento",
    "art": "🪽",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 423,
    "n": "Fusão Suprema 16",
    "a": 3275,
    "d": 2900,
    "t": "Guerreiro",
    "g": "Sol",
    "e": "Luz",
    "art": "⚔️",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 424,
    "n": "Fusão Suprema 17",
    "a": 3320,
    "d": 2940,
    "t": "Aqua",
    "g": "Netuno",
    "e": "Água",
    "art": "🌊",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  },
  {
    "id": 425,
    "n": "Fusão Suprema 18",
    "a": 3365,
    "d": 2980,
    "t": "Máquina",
    "g": "Urano",
    "e": "Raio",
    "art": "🤖",
    "rarity": "UR",
    "family": "fusao",
    "fusion": true
  }
]);
